### ISSUE TITLE
need help regardingh dynamic ids

### ISSUE THREAD

**Issue by livetvbox** [nRF24/RF24Mesh#146]
Hi
i want to use rf23mesh but i want to add all Aruino dynamically so if i add my new Aruino it will check existing ids and get new one according to.
please peovide any base example for and client for Aruino

**Comment by Avamander** [comment]
Example client:
https://github.com/nRF24/RF24Mesh/blob/master/examples/RF24Mesh_Example/RF24Mesh_Example.ino

Example base:
https://github.com/nRF24/RF24Mesh/blob/master/examples/RF24Mesh_Example_Master/RF24Mesh_Example_Master.ino

This is probably the best you're going to get because noone has written such software on top of RF24Mesh so far as far as I'm aware.
