### ISSUE TITLE
Protocol Questions

### ISSUE THREAD

**Issue by rohinrohin** [nRF24/RF24Mesh#92]
I wanted to understand how your mesh stack works. Could you please explain these few questions 
1. How are you implementing node discovery and solving flooding effect during self discovery of node. (when a node joins a network, it sends a broadcast and this is relayed until it reaches the master? - assuming that's how you implemented it). I'm not entirely clear on this. 
2. How does the master know the node's address, does it take the first relayed broadcast message from the nodes (and every relaying node will add its header address to it?)

It would be great if you could point me to a document or explain the way this mesh is implemented

Thanks for your time

**Comment by TMRh20** [comment]
It is difficult to explain RF24Mesh directly unless you are aware of RF24 &
RF24Network layers. Take a look at the diagram at
http://tmrh20.github.io/RF24Network/Tuning.html to see general topology in
RF24Network and RF24 docs/examples as required.

1. Nodes just broadcast to each multicast level looking for responses.
Attached nodes can relay information on their behalf, because un-attached
nodes can only use multicast. No 'flood' protection etc.

2. RF24Mesh uses nodeIDs. (like IP address) RF24Network uses very specific
RF24 addressing( like MAC addresses )

RF24Mesh was written in a very short time and I have not reviewed it or its
processes in detail, although I've been using it regularly. As with all the
RF24* libraries currently, the documentation, examples etc need a lot of
work, but the code & functionality are pretty good.
